baseURL = "https://ziyuanding.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
pagination.pagerSize = 10
hasCJKLanguage = true
article.showTableOfContents = true
article.showDateUpdated = true
toc = true

googleAnalytics = "G-DZPNT0R1LX"

showViews = true
showLikes = true